@Host = http://localhost:5030

### Listar todos los usuarios
GET {{Host}}/api/user/list HTTP/1.1
Content-Type: application/json

### Recuperar un usuario
GET {{Host}}/api/user/42 HTTP/1.1
Content-Type: application/json

### Cantidad de usuarios
GET {{Host}}/api/user/count HTTP/1.1
Content-Type: application/json

### Crear un usuario
POST {{Host}}/api/user/add HTTP/1.1
Content-Type: application/json

{
  "userName": "Christian",
  "passwordHash": "index#123",
  "email": "chismaquis@hotmail.com",
  "emailVerified": true,
  "fullName": "Christian Mamani Quispe",
  "phoneNumber": "15451231"
}

### Iniciar sesion
POST {{Host}}/api/user/login HTTP/1.1
Content-Type: application/json

{
  "email": "chismaquis@hotmail.com",
  "passwordHash": "index#123"
}
